export const tracks = [
    {
      title: "Save your Tears",
      src: "https://i.scdn.co/image/ab67616d0000b273f4164fac45b1d1bfb5cb5fdd",
      author: "TheWeeknd",
      id: 1,
      color: "#d42a2a",
      tags: ["Save your Tears", "The Weeknd", "Música pop"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/save-your-tears.mp3",
      backgound: "https://i.imgur.com/bo8du2Q.jpg",
    },
    {
      title: "After dark",
      src: "https://images.genius.com/587696938d43cbe1df3d6dd99094e19a.960x960x1.jpg",
      author: "MrKitty",
      id: 2,
      color: "#000000",
      tags: ["After dark", "Mr Kitty"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/after-dark.mp3",
      backgound: "https://i.imgur.com/A3KDNFL.jpg",
    },
    {
      title: "Lovely Bastards",
      src: "https://i.scdn.co/image/ab67616d0000b273226383907a53ab4c13cca8e2",
      author: "ZWE1HVNDXR",
      id: 3,
      color: "#e825d1",
      tags: ["Lovely Bastards", "ZWE1HVNDXR", "Phonk"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/lovely-bastards.mp3",
      backgound: "https://i.imgur.com/wi3tJZD.jpg",
    },
    {
      title: "SPIT IN MY FACE!",
      src: "https://i.scdn.co/image/ab67616d0000b2738871ccba23d6c8f3e4763a8a",
      author: "ThxSoMch ",
      id: 4,
      color: "#e89758",
      tags: ["SPIT IN MY FACE!", "ThxSoMch", "Post punk"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/spit-in-my-face.mp3",
      backgound: "https://i.imgur.com/fqH9dGY.jpg",
    },
    {
      title: "PRIDE",
      src: "https://images.genius.com/3505b8fdda70551d33d0436d55cdb00f.1000x1000x1.png",
      author: "Kendrick Lamar",
      id: 5,
      color: "#f75814",
      tags: ["PRIDE", "Kendrick Lamar", "Hip hop"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/pride.mp3",
      backgound: "https://i.imgur.com/Uqj2L4A.jpg",
    },
    {
      title: "Who is she",
      src: "https://i.scdn.co/image/ab67616d0000b2739a60a37a5ff1efb3ef6d1479",
      author: "i Monster",
      id: 6,
      color: "#d69c83",
      tags: ["Who is she", "i Monster", "Electronic", "Hip hop"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/who-is-she.mp3",
      backgound: "https://i.imgur.com/ZbNWbnb.jpg",
    },
    {
      title: "Aftermath",
      src: "https://i1.sndcdn.com/artworks-PbDMANfO4vOe-0-t500x500.jpg",
      author: "Caravan Palace",
      id: 7,
      color: "#006fab",
      tags: ["Aftermath", "Caravan Palace", "Electro Swing"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/aftermath.mp3",
      backgound: "https://i.imgur.com/hC0E3iE.jpg",
    },
    {
      title: "BAaTH",
      src: "https://i1.sndcdn.com/artworks-000201824536-yax09t-t500x500.jpg",
      author: "Toby Fox",
      id: 8,
      color: "#b30c0c",
      tags: [
        "BAaTH",
        "Undertale",
        "Indie",
        "Toby Fox",
        "Battle against a true hero",
      ],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/battle-against-a-true-hero.mp3",
      backgound: "https://i.imgur.com/zQKJ17Z.jpg",
    },
    {
      title: "Charm",
      src: "https://i1.sndcdn.com/artworks-OW0uCrr4tyR3gzzu-spfVLQ-t500x500.jpg",
      author: "Rema",
      id: 9,
      color: "#542513",
      tags: ["Charm", "Rema"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/charm.mp3",
      backgound: "https://i.imgur.com/ihBm4Ad.jpg",
    },
    {
      title: "21 Guns",
      src: "https://upload.wikimedia.org/wikipedia/en/0/0e/GreenDay21Guns.jpg",
      author: "Green Day",
      id: 10,
      color: "#fc3838",
      tags: ["21 Guns", "Green Day", "Punk rock"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/21guns.mp3",
      backgound: "https://i.imgur.com/5jMynQQ.jpg",
    },
    {
      title: "Bzrp Music Vol. 57",
      src: "https://i1.sndcdn.com/artworks-aW8th19cq4EF-0-t500x500.jpg",
      author: "Bzrp & Milo J",
      id: 11,
      color: "#969595",
      tags: ["Bzrp", "Bizarap", "Milo J", " hoy me voy al sol"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/bzrp-miloj.mp3",
      backgound: "https://i.imgur.com/MhLzfcl.png",
    },
    {
      title: "Aria Math",
      src: "https://virtualpiano.net/wp-content/uploads/2020/11/Aria-Math-Minecraft-C418-Best-Online-Piano-Keyboard-Virtual-Piano.jpg",
      author: "C418",
      id: 12,
      color: "#ffbb0f",
      tags: ["Aria Math", "C418", "Mojang", "Notch", "Mine Craft"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/aria-math.mp3",
      backgound: "https://media.tenor.com/hqTqZSZlJJcAAAAd/aria-math-c418.gif",
    },
    {
      title: "Megalovania",
      src: "https://i1.sndcdn.com/artworks-000256712201-xxvmej-t500x500.jpg",
      author: "Toby Fox",
      id: 13,
      color: "#bfe0ff",
      tags: ["Megalovania", "Toby Fox", "Undertale", "Sans", "Chara"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/megalovania.mp3",
      backgound:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOZPwD5xPsPZo9GdDE4vGG7jbiNxg4QC7prw&usqp=CAU",
    },
    {
      title: "Subwoofer Lullaby",
      src: "https://i1.sndcdn.com/artworks-000125935263-w7tj4e-t500x500.jpg",
      author: "C418",
      id: 14,
      color: "#32a852",
      tags: ["Subwoofer Lullaby", "C418", "Mine craft", "Mojang"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/subwoofer-lullaby.mp3",
      background: "https://i.ytimg.com/vi/QLsBLxvcqBs/maxresdefault.jpg",
    },
    {
      title: "Enter Hallownest",
      src: "https://i1.sndcdn.com/artworks-P4oLMOA72tyiEol5-z52ONw-t500x500.jpg",
      author: "Christopher Larkin",
      id: 15,
      color: "#3d392c",
      tags: ["Enter Hallownest", "Christopher Larkin", "Hollow Knight", "Indie"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/enter-hallownest.mp3",
      background: "https://i.ytimg.com/vi/gm4ZSGPne4k/maxresdefault.jpg",
    },
    {
      title: "Dirtmouth",
      src: "https://pm1.aminoapps.com/7600/2e8bd05f9db5f8c178a306b255aa13b437070905r1-1338-1001v2_hq.jpg",
      author: "Christopher Larkin",
      id: 16,
      color: "#40362f",
      tags: ["Dirth Mouth", "Christopher Larkin", "Hollow Knight", "Indie"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/dirtmouth.mp3",
      background: "https://i.ytimg.com/vi/gm4ZSGPne4k/maxresdefault.jpg",
    },
    {
      title: "Greenpath",
      src: "https://i1.sndcdn.com/artworks-rVbXpruqngdAHWYh-GbV7SQ-t500x500.jpg",
      author: "Christopher Larkin",
      id: 17,
      color: "#40362f",
      tags: ["Green Path", "Christopher Larkin", "Hollow Knight", "Indie"],
      mp3: "https://yosseferrazik.github.io/jukebox-music-host/greenpath.mp3",
      background:
        "https://i1.sndcdn.com/artworks-rVbXpruqngdAHWYh-GbV7SQ-t500x500.jpg",
    },
  ];
  